sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
  # required when sudo: required for the Ruby petstore tests
  - gem install bundler

install:

script:
  - mvn package

addons:
  artifacts:
    paths:
      - $(ls ./modules/swagger-codegen-cli/target/*.jar | tr "\n" ":")

cache:
  directories:
    - $HOME/.m2