sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
  # required when sudo: required for the Ruby petstore tests
  - gem install bundler

install:

script:
  - mvn package -Dmaven.test.skip=true

after_success:
  - cp ./modules/swagger-codegen-cli/target/*.jar .

addons:
  artifacts:
    paths:
      - $(ls *.jar | tr "\n" ":")

cache:
  directories:
    - $HOME/.m2