sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
  # required when sudo: required for the Ruby petstore tests
  - gem install bundler

install:

script:
  - mvn package

before_deploy:
  - cp ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar .
addons:
  artifacts:
    paths:
      - $(ls ./swagger-codegen-cli.jar | tr "\n" ":")

cache:
  directories:
    - $HOME/.m2